# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VasiliyLu.WindowsCleanupManager
PackageVersion: 0.2.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: wcm.exe
  PortableCommandAlias: wcm
Commands:
- wcm
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/VasiliyLu/WindowsCleanupManager/releases/download/v0.2.0/wcm-0.2.0-win-x64.zip
  InstallerSha256: 69424CE119EBB1BE706E0BD0E01F08212DF6146DF1B88F32DD4453F100DEFD1B
- Architecture: arm64
  InstallerUrl: https://github.com/VasiliyLu/WindowsCleanupManager/releases/download/v0.2.0/wcm-0.2.0-win-arm64.zip
  InstallerSha256: 3CDCB5063959B2B4BE0078594B0006B440B8748147AC26DEC1DB55B2572431FA
ManifestType: installer
ManifestVersion: 1.12.0
